dashboard_dashboard:
    resource: "@DashboardDashboardBundle/Controller/"
    type:     annotation
    prefix:   /

elycee_elycee:
    resource: "@ElyceeElyceeBundle/Controller/"
    type:     annotation

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
